export const colors = {
  background: '#fcf9f3',
  primary: '#000614',
  onPrimary: '#ffffff',
  secondary: '#ad3318',
  onSecondary: '#ffffff',
  surface: '#fcf9f3',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f6f3ed',
  surfaceContainer: '#f0eee8',
  surfaceContainerHigh: '#ebe8e2',
  surfaceVariant: '#e5e2dc',
  onSurface: '#1c1c18',
  onSurfaceVariant: '#44474d',
  outline: '#75777d',
  outlineVariant: '#c5c6cd',
  tertiaryFixed: '#d2e8da',
  secondaryContainer: '#ff6e4d',
  onSecondaryContainer: '#681000',
  tertiary: '#000703',
} as const
